### ISSUE TITLE
"Foundation is not a function" error

### ISSUE THREAD

**Issue by nickpish** [g-kanoufi/genesis-foundation6-child-theme#3]
Hi, thank you for your work on this theme-- it's absolutely fantastic. One issue I'm having is that on certain pages I'm getting an `Uncaught TypeError: $(...).foundation is not a function` in my console related to this script:

``` javascript
;(function($){
    $(document).foundation({
        orbit : {
            stack_on_small: true, slide_number: false, variable_height: true
        },
        magellan : {
            destination_threshold: 120,
            throttle_delay: 25,
            fixed_top: 45
        }
    });
})(jQuery);
```

I've placed this in the `scripts.js` file included in your theme, and I'm just trying to initialize some Foundation components in the page. Do you know what might be going on here? Thanks for any assistance.

**Comment by g-kanoufi** [comment]
Hi Nick,

Could you try to add all your foundation related js inside the app.js file, this should resolve your issue.

Let me know if this work for you.
